apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: GEN-AI
  description: Gemini is a series of generative AI models developed by Google
spec:
  type: geminiapi
  lifecycle: development
  owner: meeran
  system: production
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Artist API
      license:
        name: MIT
    servers:
      - url: http://artist.spotify.net/v1
    paths:
      /artists:
        get:
          summary: List all artists
    ...
